version: "3.9"

services:
  db:
    image: postgres
    container_name: django_stock50_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    container_name: django_stock50_web
    restart: always
    entrypoint: /app/docker-entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8088
    volumes:
      - .:/app
    ports:
      - "8088:8088"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Asia/Taipei
    depends_on:
      - db
  django-q:
    build: .
    container_name: django_stock50_django_q
    restart: always
    command: python manage.py qcluster
    volumes:
      - .:/app

volumes:
  postgres_data: